name: Git tag

on:
  push:
    branches: [master]

jobs:
  container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Save the version to an environment file
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - run: git tag ${VERSION}

      - run: git push origin ${VERSION}
