name: Git tag

on:
  push:
    branches: [master]

jobs:
  container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - run: git tag ${{ github.sha }}

      - run: git push origin ${{ github.sha }}
